export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CLEAR_CART = "CLEAR_CART";

export const INCREASE_CART_PRICE = "INCREASE_CART_PRICE";

export const DECREASE_CART_PRICE = "DECREASE_CART_PRICE";

export const RESET_CART_PRICE = "RESET_CART_PRICE";
